version: '3.8'
services:
  # postgres-user:
  #   image: postgres
  #   container_name: postgres-user
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: userdb
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - user_data:/var/lib/postgresql/data

  postgres-product:
    image: postgres
    container_name: postgres-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      # - user-service
      - product-service
      - rabbitmq
    environment:
      - NODE_ENV=development

  # user-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/user-service/Dockerfile
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres-user
  #     - rabbitmq
  #   environment:
  #     - NODE_ENV=development

  product-service:
    build:
      context: .
      dockerfile: ./apps/product-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres-product
      - rabbitmq
    environment:
      - NODE_ENV=development

volumes:
  # user_data:
  product_data:
